### ISSUE TITLE
Why you calculate LossAB and LossBA?

### ISSUE THREAD

**Issue by hellopipu** [tmquan/RefineGAN#15]
Hi,

Thanks for your code.

I can't understand the LossAB and LossBA [here](https://github.com/tmquan/RefineGAN/blob/a5222b3517ebe5b29613859db4470d2eea233208/RefineGAN.py#L179)

Using the LossAB, you force the reconstructed images from sample B to be the same as sample A. It's hard for me to understand. Could you give me some hint or explanation on this. 

And is it appropriate to conclude that the cyclic loss is just calculate the reconstruction loss from both image domain and k-space domain?

**Comment by tmquan** [comment]
Hi, thank for asking. 

As you can see in the scope of LossAB
```python
G_loss_AB, D_loss_AB = self.build_losses(S1_dis_real, S2_dis_fake, name='AB')
G_loss_Ab, D_loss_Ab = self.build_losses(S1_dis_real, T2_dis_fake, name='Ab')
```
It only build the Adversarial loss of real sample (true) and output from the network (fake). It doesnot calculate the per-pixel reconstruction loss since S01 and S2 are different samples. 

The cyclic loss implemented in this way is stochastic across samples (randomly drawing two from the datasets) and domains (image and frequency). 

Hope that this addresses your question.

**Comment by hellopipu** [comment]
Thanks, I get it.
